export const USER_SIGN_IN_API = 'USER_SIGN_IN_API'
export const USLOGIN = 'USLOGIN' 



export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA'
export const GET_ALL_PROJECT_CATEGORY = 'GET_ALL_PROJECT_CATEGORY'
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA'
export const GET_LIST_PROJECT_SAGA = 'GET_LIST_PROJECT_SAGA'
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA'
export const GET_PROJECT_DETAIL_SAGA ='GET_PROJECT_DETAIL_SAGA'



export const OPEN_DRAWER = 'OPEN_DRAWER'
export const CLOSE_DRAWER = 'CLOSE_DRAWER'
export const OPEN_FORM_EDIT = 'OPEN_FORM_EDIT'
export const SET_SUBMIT_EDIT_PROJECT = 'SET_SUBMIT_EDIT_PROJECT'
export const SET_SUBMIT_CREATE_TASK = 'SET_SUBMIT_CREATE_TASK'
export const OPEN_FORM_CREATE_TASK = 'OPEN_FORM_CREATE_TASK'
export const SET_DISABLED_SUBMIT = 'SET_DISABLED_SUBMIT'



export const EDIT_PROJECT = 'EDIT_PROJECT'