export const GET_ALL_PROJECT = 'GET_All_PROJECT'
export const GET_LIST_PROJECT = 'GET_LIST_PROJECT'
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA'
export const PUT_PROJECT_DETAIL = 'PUT_PROJECT_DETAIL'


export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA'